/** Google Material Symbols names for cards, nav, and headers */
export const MaterialIcons = {
  shieldCheck: 'verified_user',
  info: 'info',
  fileText: 'description',
  calendar: 'calendar_month',
  globe: 'public',
  gavel: 'balance',
  files: 'folder_open',
  upload: 'upload',
  user: 'person',
  activity: 'timeline',
  flag: 'flag',
  bot: 'smart_toy',
  messageCircle: 'chat',
  dollarSign: 'payments',
  shield: 'shield',
  clock: 'schedule',
  users: 'group',
  building: 'business',
  stethoscope: 'medical_services',
  alertTriangle: 'warning',
  send: 'send',
  mail: 'mail',
  plus: 'add',
  calculator: 'calculate',
  mapPin: 'location_on',
  settings: 'settings',
  refreshCw: 'refresh',
  receipt: 'receipt_long',
  userSearch: 'person_search',
  globe2: 'travel_explore',
  microscope: 'biotech',
  sparkles: 'auto_awesome',
  check: 'check',
} as const

export type MaterialIconKey = keyof typeof MaterialIcons

export const NAV_MATERIAL_ICONS: Record<string, string> = {
  'case-context': MaterialIcons.info,
  'event-details': MaterialIcons.fileText,
  'claimant-details': MaterialIcons.user,
  'policy-info': MaterialIcons.dollarSign,
  documents: MaterialIcons.files,
  integrations: MaterialIcons.globe,
  medical: MaterialIcons.stethoscope,
  referral: MaterialIcons.send,
  worksheet: MaterialIcons.activity,
  tools: MaterialIcons.settings,
  comms: MaterialIcons.mail,
  decision: MaterialIcons.gavel,
}
